### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by 3D3C** [dragonlee258079/DMT#1]
在运行时，此处出现错误File "/home/dingchuang/Desktop/DMT-main/dataset.py", line 266, in __getitem__
    img = Image.open(img_path).convert('RGB')。
提示找不到对应目录：FileNotFoundError: [Errno 2] No such file or directory: '/home/dingchuang/Desktop/DMT-main/dataset/train_data/DUTS_class_syn/img_png_seamless_cloning_add_naive/img/354/sun_ayjymvvkylqixram_syn1.png'
其中img_png_seamless_cloning_add_naive是DUTX_class_syn对应目录下，sun_ayjymvvkylqixram_syn1.png在DUTX_class目录下

整体的运行报错提示如下所示：
Starting epoch 1/300.
epoch: 0 ------ lr:1.0000000000000001e-07
/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/nn/functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/dingchuang/Desktop/DMT-main/train.py:455: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
Whole iter step:1 - epoch progress:0/300 - total_loss:9.0792 - f_co_bce:0.7500 - f_bg_bce: 0.7476 - f_com_bce: 0.7089 - f_iou: 0.8081 - f_iou_com: 0.7896 - s_co_bce:0.7403 - s_bg_bce: 0.7326 - s_com_bce: 0.7389 - s_co_1_bce: 0.7324 - s_co_2_bce: 0.7324 - s_iou:0.7186 - s_iou_com:0.8048  batch_size: 0.8073975443840027
/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/nn/functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/dingchuang/Desktop/DMT-main/train.py:455: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
Whole iter step:2 - epoch progress:0/300 - total_loss:8.4906 - f_co_bce:0.7740 - f_bg_bce: 0.7094 - f_com_bce: 0.7522 - f_iou: 0.6565 - f_iou_com: 0.6503 - s_co_bce:0.7252 - s_bg_bce: 0.7334 - s_com_bce: 0.7535 - s_co_1_bce: 0.7230 - s_co_2_bce: 0.7230 - s_iou:0.7263 - s_iou_com:0.6382  batch_size: 0.6486390233039856
/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/nn/functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/dingchuang/Desktop/DMT-main/train.py:455: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
Whole iter step:3 - epoch progress:0/300 - total_loss:8.9453 - f_co_bce:0.7329 - f_bg_bce: 0.7725 - f_com_bce: 0.7207 - f_iou: 0.7551 - f_iou_com: 0.7502 - s_co_bce:0.7417 - s_bg_bce: 0.7155 - s_com_bce: 0.7662 - s_co_1_bce: 0.7338 - s_co_2_bce: 0.7338 - s_iou:0.7195 - s_iou_com:0.7647  batch_size: 0.7724191546440125
/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/nn/functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/dingchuang/Desktop/DMT-main/train.py:455: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
Whole iter step:4 - epoch progress:0/300 - total_loss:8.7664 - f_co_bce:0.7437 - f_bg_bce: 0.7964 - f_com_bce: 0.7850 - f_iou: 0.6863 - f_iou_com: 0.7035 - s_co_bce:0.7413 - s_bg_bce: 0.7170 - s_com_bce: 0.7443 - s_co_1_bce: 0.7305 - s_co_2_bce: 0.7305 - s_iou:0.7365 - s_iou_com:0.6902  batch_size: 0.6915693283081055
/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/nn/functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/dingchuang/Desktop/DMT-main/train.py:455: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
Whole iter step:5 - epoch progress:0/300 - total_loss:8.5702 - f_co_bce:0.8220 - f_bg_bce: 0.6594 - f_com_bce: 0.7281 - f_iou: 0.6952 - f_iou_com: 0.6588 - s_co_bce:0.7347 - s_bg_bce: 0.7406 - s_com_bce: 0.7437 - s_co_1_bce: 0.7229 - s_co_2_bce: 0.7229 - s_iou:0.7256 - s_iou_com:0.6678  batch_size: 0.6714513897895813
/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/nn/functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/dingchuang/Desktop/DMT-main/train.py:455: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
Whole iter step:6 - epoch progress:0/300 - total_loss:9.6683 - f_co_bce:0.7263 - f_bg_bce: 0.7763 - f_com_bce: 0.7291 - f_iou: 0.9440 - f_iou_com: 0.9417 - s_co_bce:0.7426 - s_bg_bce: 0.7232 - s_com_bce: 0.7464 - s_co_1_bce: 0.7223 - s_co_2_bce: 0.7223 - s_iou:0.7232 - s_iou_com:0.9469  batch_size: 0.9463717341423035
/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/nn/functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/dingchuang/Desktop/DMT-main/train.py:455: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
Whole iter step:7 - epoch progress:0/300 - total_loss:9.3406 - f_co_bce:0.7334 - f_bg_bce: 0.7540 - f_com_bce: 0.7076 - f_iou: 0.8679 - f_iou_com: 0.8593 - s_co_bce:0.7373 - s_bg_bce: 0.7240 - s_com_bce: 0.7577 - s_co_1_bce: 0.7231 - s_co_2_bce: 0.7231 - s_iou:0.7302 - s_iou_com:0.8700  batch_size: 0.8759831786155701
/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/nn/functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/dingchuang/Desktop/DMT-main/train.py:455: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
Whole iter step:8 - epoch progress:0/300 - total_loss:9.6095 - f_co_bce:0.7746 - f_bg_bce: 0.7279 - f_com_bce: 0.7352 - f_iou: 0.9385 - f_iou_com: 0.9240 - s_co_bce:0.7325 - s_bg_bce: 0.7375 - s_com_bce: 0.7364 - s_co_1_bce: 0.7157 - s_co_2_bce: 0.7157 - s_iou:0.7394 - s_iou_com:0.9222  batch_size: 0.9255352020263672
/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/nn/functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/dingchuang/Desktop/DMT-main/train.py:455: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
Whole iter step:9 - epoch progress:0/300 - total_loss:9.2548 - f_co_bce:0.7078 - f_bg_bce: 0.7696 - f_com_bce: 0.7403 - f_iou: 0.8464 - f_iou_com: 0.8530 - s_co_bce:0.7097 - s_bg_bce: 0.7596 - s_com_bce: 0.7241 - s_co_1_bce: 0.7281 - s_co_2_bce: 0.7281 - s_iou:0.7181 - s_iou_com:0.8459  batch_size: 0.8522436022758484
/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/nn/functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/dingchuang/Desktop/DMT-main/train.py:455: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
Whole iter step:10 - epoch progress:0/300 - total_loss:8.4993 - f_co_bce:0.6622 - f_bg_bce: 0.8041 - f_com_bce: 0.6912 - f_iou: 0.6544 - f_iou_com: 0.6652 - s_co_bce:0.7154 - s_bg_bce: 0.7458 - s_com_bce: 0.7365 - s_co_1_bce: 0.7196 - s_co_2_bce: 0.7196 - s_iou:0.7391 - s_iou_com:0.6794  batch_size: 0.6863174438476562
/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/nn/functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/dingchuang/Desktop/DMT-main/train.py:455: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
Whole iter step:11 - epoch progress:0/300 - total_loss:9.3552 - f_co_bce:0.7248 - f_bg_bce: 0.7594 - f_com_bce: 0.8072 - f_iou: 0.8343 - f_iou_com: 0.8642 - s_co_bce:0.7307 - s_bg_bce: 0.7320 - s_com_bce: 0.7505 - s_co_1_bce: 0.7229 - s_co_2_bce: 0.7229 - s_iou:0.7430 - s_iou_com:0.8385  batch_size: 0.8476535081863403
Traceback (most recent call last):
  File "/home/dingchuang/Desktop/DMT-main/train.py", line 540, in <module>
    main(args)
  File "/home/dingchuang/Desktop/DMT-main/train.py", line 445, in main
    for iteration, data_batch in enumerate(train_loader):
  File "/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dingchuang/Desktop/DMT-main/dataset.py", line 266, in __getitem__
    img = Image.open(img_path).convert('RGB')
  File "/home/dingchuang/conda/envs/yolo/lib/python3.7/site-packages/PIL/Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/dingchuang/Desktop/DMT-main/dataset/train_data/DUTS_class_syn/img_png_seamless_cloning_add_naive/img/354/sun_ayjymvvkylqixram_syn1.png'

**Comment by 3D3C** [comment]
您好，我把代码重新下载了一份，运行之后还是同样的问题
FileNotFoundError: [Errno 2] No such file or directory: '/home/dingchuang/Desktop/DMT-main/dataset/train_data/DUTS_class_syn/img_png_seamless_cloning_add_naive/img/89/n01819313_7029_syn1.png'
我下载的数据集应该也没有问题

**Comment by dragonlee258079** [comment]
好的，我重新检查一下代码和数据

**Comment by 3D3C** [comment]
您好，在dataset.py的238行：select_num = random.randint(1, 5)，如果固定为select_num = 4是可以正常运行的，
但在选择syn img和reverse syn img时就会出现这个问题。

**Comment by dragonlee258079** [comment]
你好，我重新下载代码和数据能顺利跑完一个epoch，你看看是不是将数据part-1和part-2合并的时候出现什么问题

**Comment by 3D3C** [comment]
好嘞，我把数据集重新处理一下
